const items =  [
    { id: 1, name: 'vitamin-d3-drops', mainCategory: 'Capsules', subCategory: 'Analgesic & Anti-Inflammatory' },
    { id: 2, name: 'multivitamin-oral-spray', mainCategory: 'Tablets', subCategory: 'Dry Syrup' },
    { id: 3, name: 'iron-oral-spray', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 4, name: 'immunity-booster-spray', mainCategory: 'Sachets', subCategory: '' },
    { id: 5, name: 'Losartan', mainCategory: 'Capsules', subCategory: 'Antacid' },
    { id: 6, name: 'Amlodipine', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 7, name: 'Gabapentin', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 8, name: 'Metoprolol', mainCategory: 'Sachets', subCategory: '' },
    { id: 9, name: 'Hydrochlorothiazide', mainCategory: 'Suspensions', subCategory: 'Antacid' },
    { id: 10, name: 'Levothyroxine', mainCategory: 'Tablets', subCategory: '' },
    { id: 11, name: 'Atenolol', mainCategory: 'Sachets', subCategory: '' },
    { id: 12, name: 'Simvastatin', mainCategory: 'Sachets', subCategory: '' },
    { id: 13, name: 'Aripiprazole', mainCategory: 'Tablets', subCategory: '' },
    { id: 14, name: 'Escitalopram', mainCategory: 'Capsules', subCategory: '' },
    { id: 15, name: 'Duloxetine', mainCategory: 'Tablets', subCategory: '' },
    { id: 16, name: 'Sertraline', mainCategory: 'Syrups', subCategory: 'Dry Syrup' },
    { id: 17, name: 'Fluoxetine', mainCategory: 'Suspensions', subCategory: 'Analgesic & Anti-Inflammatory' },
    { id: 18, name: 'Citalopram', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 19, name: 'Alprazolam', mainCategory: 'Tablets', subCategory: '' },
    { id: 20, name: 'Lorazepam', mainCategory: 'Capsules', subCategory: 'Analgesic & Anti-Inflammatory' },
    { id: 21, name: 'Clonazepam', mainCategory: 'Tablets', subCategory: '' },
    { id: 22, name: 'Diazepam', mainCategory: 'Syrups', subCategory: 'Dry Syrup' },
    { id: 23, name: 'Hydroxyzine', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 24, name: 'Warfarin', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 25, name: 'Clopidogrel', mainCategory: 'Capsules', subCategory: '' },
    { id: 26, name: 'Dabigatran', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 27, name: 'Rivaroxaban', mainCategory: 'Capsules', subCategory: '' },
    { id: 28, name: 'Enalapril', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 29, name: 'Ramipril', mainCategory: 'Capsules', subCategory: '' },
    { id: 30, name: 'Benazepril', mainCategory: 'Sachets', subCategory: '' },
    { id: 31, name: 'Amlodipine-Benazepril', mainCategory: 'Tablets', subCategory: '' },
    { id: 32, name: 'Nifedipine', mainCategory: 'Capsules', subCategory: '' },
    { id: 33, name: 'Verapamil', mainCategory: 'Sachets', subCategory: '' },
    { id: 34, name: 'Diltiazem', mainCategory: 'Suspensions', subCategory: 'Antacid' },
    { id: 35, name: 'Lansoprazole', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 36, name: 'Pantoprazole', mainCategory: 'Tablets', subCategory: '' },
    { id: 37, name: 'Rabeprazole', mainCategory: 'Capsules', subCategory: '' },
    { id: 38, name: 'Esomeprazole', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 39, name: 'Furosemide', mainCategory: 'Suspensions', subCategory: 'Analgesic & Anti-Inflammatory' },
    { id: 40, name: 'HCTZ (Hydrochlorothiazide)', mainCategory: 'Tablets', subCategory: '' },
    { id: 41, name: 'Bumetanide', mainCategory: 'Capsules', subCategory: '' },
    { id: 42, name: 'Torsemide', mainCategory: 'Sachets', subCategory: '' },
    { id: 43, name: 'Spironolactone', mainCategory: 'Capsules', subCategory: '' },
    { id: 44, name: 'Eplerenone', mainCategory: 'Suspensions', subCategory: 'Analgesic & Anti-Inflammatory' },
    { id: 45, name: 'Isosorbide Mononitrate', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 46, name: 'Nitroglycerin', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 47, name: 'Digoxin', mainCategory: 'Capsules', subCategory: '' },
    { id: 48, name: 'Amiodarone', mainCategory: 'Tablets', subCategory: '' },
    { id: 49, name: 'Lisinopril-Hydrochlorothiazide', mainCategory: 'Capsules', subCategory: '' },
    { id: 50, name: 'Losartan-Hydrochlorothiazide', mainCategory: 'Tablets', subCategory: '' },
    { id: 51, name: 'Amlodipine-Besylate', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 52, name: 'Metoprolol Tartrate', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 53, name: 'Metoprolol Succinate', mainCategory: 'Tablets', subCategory: '' },
    { id: 54, name: 'Carvedilol', mainCategory: 'Sachets', subCategory: '' },
    { id: 55, name: 'Propranolol', mainCategory: 'Capsules', subCategory: '' },
    { id: 57, name: 'Clonidine', mainCategory: 'Syrups', subCategory: 'Cough Syrup' },
    { id: 58, name: 'Doxazosin', mainCategory: 'Tablets', subCategory: '' },
    { id: 59, name: 'Terazosin', mainCategory: 'Capsules', subCategory: '' },
    { id: 60, name: 'Finasteride', mainCategory: 'Sachets', subCategory: '' },
    { id: 61, name: 'Dutasteride', mainCategory: 'Suspensions', subCategory: 'Antacid' },
    { id: 62, name: 'Tamsulosin', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 63, name: 'Allopurinol', mainCategory: 'Sachets', subCategory: '' },
    { id: 64, name: 'Colchicine', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 65, name: 'Febuxostat', mainCategory: 'Syrups', subCategory: 'Dry Syrup' },
    { id: 66, name: 'Prednisone', mainCategory: 'Sachets', subCategory: '' },
    { id: 67, name: 'Methylprednisolone', mainCategory: 'Tablets', subCategory: '' },
    { id: 68, name: 'Dexamethasone', mainCategory: 'Capsules', subCategory: '' },
    { id: 69, name: 'Hydrocortisone', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 70, name: 'Fluticasone', mainCategory: 'Tablets', subCategory: '' },
    { id: 71, name: 'Budesonide', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 72, name: 'Montelukast', mainCategory: 'Sachets', subCategory: '' },
    { id: 73, name: 'Zafirlukast', mainCategory: 'Suspensions', subCategory: 'Antacid' },
    { id: 74, name: 'Cromolyn', mainCategory: 'Capsules', subCategory: '' },
    { id: 75, name: 'Leukotriene Receptor Antagonists', mainCategory: 'Sachets', subCategory: '' },
    { id: 76, name: 'Inhaled Corticosteroids', mainCategory: 'Tablets', subCategory: '' },
    { id: 77, name: 'Combination Inhalers', mainCategory: 'Sachets', subCategory: '' },
    { id: 78, name: 'Albuterol', mainCategory: 'Suspensions', subCategory: 'Antacid' },
    { id: 79, name: 'Levalbuterol', mainCategory: 'Syrups', subCategory: 'Dry Syrup' },
    { id: 80, name: 'Ipratropium-Albuterol', mainCategory: 'Capsules', subCategory: '' },
    { id: 81, name: 'Tiotropium', mainCategory: 'Tablets', subCategory: '' },
    { id: 82, name: 'Oxybutynin', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 83, name: 'Tolterodine', mainCategory: 'Capsules', subCategory: '' },
    { id: 84, name: 'Solifenacin', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 85, name: 'Darifenacin', mainCategory: 'Tablets', subCategory: '' },
    { id: 86, name: 'Trospium', mainCategory: 'Sachets', subCategory: '' },
    { id: 87, name: 'Fesoterodine', mainCategory: 'Suspensions', subCategory: 'Asal Sprays' },
    { id: 88, name: 'Sildenafil', mainCategory: 'Capsules', subCategory: '' },
    { id: 89, name: 'Tadalafil', mainCategory: 'Syrups', subCategory: 'Drops' },
    { id: 90, name: 'Vardenafil', mainCategory: 'Tablets', subCategory: '' },
    { id: 96, name: 'Fluconazole', mainCategory: 'Sachets', subCategory: '' },
    { id: 97, name: 'Ketoconazole', mainCategory: 'Suspensions', subCategory: 'Antacid' },
    { id: 98, name: 'Clotrimazole', mainCategory: 'Capsules', subCategory: '' },
    { id: 99, name: 'Miconazole', mainCategory: 'Sachets', subCategory: '' },
    { id: 100, name: 'Nystatin', mainCategory: 'Tablets', subCategory: '' },
    ];
  

export default items;
