const items = [
    { id: 1, name: 'vitamin-d3-drops' },
    { id: 2, name: 'multivitamin-oral-spray' },
    { id: 3, name: 'iron-oral-spray' },
    { id: 4, name: 'immunity-booster-spray' },
    { id: 5, name: 'Losartan' },
    { id: 6, name: 'Amlodipine' },
    { id: 7, name: 'Gabapentin' },
    { id: 8, name: 'Metoprolol' },
    { id: 9, name: 'Hydrochlorothiazide' },
    { id: 10, name: 'Levothyroxine' },
    { id: 11, name: 'Atenolol' },
    { id: 12, name: 'Simvastatin' },
    { id: 13, name: 'Aripiprazole' },
    { id: 14, name: 'Escitalopram' },
    { id: 15, name: 'Duloxetine' },
    { id: 16, name: 'Sertraline' },
    { id: 17, name: 'Fluoxetine' },
    { id: 18, name: 'Citalopram' },
    { id: 19, name: 'Alprazolam' },
    { id: 20, name: 'Lorazepam' },
    { id: 21, name: 'Clonazepam' },
    { id: 22, name: 'Diazepam' },
    { id: 23, name: 'Hydroxyzine' },
    { id: 24, name: 'Warfarin' },
    { id: 25, name: 'Clopidogrel' },
    { id: 26, name: 'Dabigatran' },
    { id: 27, name: 'Rivaroxaban' },
    { id: 28, name: 'Enalapril' },
    { id: 29, name: 'Ramipril' },
    { id: 30, name: 'Benazepril' },
    { id: 31, name: 'Amlodipine-Benazepril' },
    { id: 32, name: 'Nifedipine' },
    { id: 33, name: 'Verapamil' },
    { id: 34, name: 'Diltiazem' },
    { id: 35, name: 'Lansoprazole' },
    { id: 36, name: 'Pantoprazole' },
    { id: 37, name: 'Rabeprazole' },
    { id: 38, name: 'Esomeprazole' },
    { id: 39, name: 'Furosemide' },
    { id: 40, name: 'HCTZ (Hydrochlorothiazide)' },
    { id: 41, name: 'Bumetanide' },
    { id: 42, name: 'Torsemide' },
    { id: 43, name: 'Spironolactone' },
    { id: 44, name: 'Eplerenone' },
    { id: 45, name: 'Isosorbide Mononitrate' },
    { id: 46, name: 'Nitroglycerin' },
    { id: 47, name: 'Digoxin' },
    { id: 48, name: 'Amiodarone' },
    { id: 49, name: 'Lisinopril-Hydrochlorothiazide' },
    { id: 50, name: 'Losartan-Hydrochlorothiazide' },
    { id: 51, name: 'Amlodipine-Besylate' },
    { id: 52, name: 'Metoprolol Tartrate' },
    { id: 53, name: 'Metoprolol Succinate' },
    { id: 54, name: 'Carvedilol' },
    { id: 55, name: 'Propranolol' },
    { id: 56, name: 'Atenolol' },
    { id: 57, name: 'Clonidine' },
    { id: 58, name: 'Doxazosin' },
    { id: 59, name: 'Terazosin' },
    { id: 60, name: 'Finasteride' },
    { id: 61, name: 'Dutasteride' },
    { id: 62, name: 'Tamsulosin' },
    { id: 63, name: 'Allopurinol' },
    { id: 64, name: 'Colchicine' },
    { id: 65, name: 'Febuxostat' },
    { id: 66, name: 'Prednisone' },
    { id: 67, name: 'Methylprednisolone' },
    { id: 68, name: 'Dexamethasone' },
    { id: 69, name: 'Hydrocortisone' },
    { id: 70, name: 'Fluticasone' },
    { id: 71, name: 'Budesonide' },
    { id: 72, name: 'Montelukast' },
    { id: 73, name: 'Zafirlukast' },
    { id: 74, name: 'Cromolyn' },
    { id: 75, name: 'Leukotriene Receptor Antagonists' },
    { id: 76, name: 'Inhaled Corticosteroids' },
    { id: 77, name: 'Combination Inhalers' },
    { id: 78, name: 'Albuterol' },
    { id: 79, name: 'Levalbuterol' },
    { id: 80, name: 'Ipratropium-Albuterol' },
    { id: 81, name: 'Tiotropium' },
    { id: 82, name: 'Oxybutynin' },
    { id: 83, name: 'Tolterodine' },
    { id: 84, name: 'Solifenacin' },
    { id: 85, name: 'Darifenacin' },
    { id: 86, name: 'Trospium' },
    { id: 87, name: 'Fesoterodine' },
    { id: 88, name: 'Sildenafil' },
    { id: 89, name: 'Tadalafil' },
    { id: 90, name: 'Vardenafil' },
    { id: 91, name: 'Finasteride' },
    { id: 92, name: 'Dutasteride' },
    { id: 93, name: 'Sildenafil' },
    { id: 94, name: 'Tadalafil' },
    { id: 95, name: 'Vardenafil' },
    { id: 96, name: 'Fluconazole' },
    { id: 97, name: 'Ketoconazole' },
    { id: 98, name: 'Clotrimazole' },
    { id: 99, name: 'Miconazole' },
    { id: 100, name: 'Nystatin' }
]
  
export default items;